### ISSUE TITLE
no haml?

### ISSUE THREAD

**Issue by halfling-rram** [disyukvitaliy/crm#1]
so good & usefull project.. but why without haml?

**Comment by disyukvitaliy** [comment]
Please take ours apologise. We will add it soon.

**Comment by disyukvitaliy** [comment]
Had been resolved
[commit](https://github.com/disyukvitaliy/crm/commit/5503eba8193bbfb245eac61a0e6e4f99613ebe23)

**Comment by halfling-rram** [comment]
looks good!
